### PR TITLE
Gradle upgrade: 3.5.1

### PR DESCRIPTION
**Pull request by jubeira**
Upgrading Gradle version to 3.5.1.

### CODE REVIEW

**Comment by ernestmc** [comment]
@jubeira can you fix this warning:
```
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_ets8zxn0zl8mjltfe7e9z5irh.run(/home/ecorbellini/repos/rosjava/src/zeroconf_jmdns_suite/build.gradle:25)
```

**Comment by jubeira** [comment]
@ernestmc note that this warning comes from the line `apply plugin: 'catkin'`. This happens because this buildscript uses the `catkin` plugin which is in `rosjava_bootstrap`, that has one `<<` operator. https://github.com/rosjava/rosjava_bootstrap/pull/64 fixes the issue; if you compile the `catkin` plugin with `catkin_make` in the same workspace, this warning should go off.

**Comment by jubeira** [comment]
This is my output when building the project after compiling (and sourcing) the whole `rosjava` workspace with catkin with the changes in `rosjava_bootstrap`:
```
juan@Sullust:~/rosjava_dev/src/zeroconf_jmdns_suite$ ./gradlew build
:jmdns:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
:jmdns:processResources NO-SOURCE
:jmdns:classes
:jmdns:jar
:jmdns:assemble
:jmdns:compileTestJava NO-SOURCE
:jmdns:processTestResources NO-SOURCE
:jmdns:testClasses UP-TO-DATE
:jmdns:test NO-SOURCE
:jmdns:check UP-TO-DATE
:jmdns:build
:jmdns_tutorials:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
:jmdns_tutorials:processResources NO-SOURCE
:jmdns_tutorials:classes
:jmdns_tutorials:jar
:jmdns_tutorials:startScripts
:jmdns_tutorials:distTar
:jmdns_tutorials:distZip
:jmdns_tutorials:assemble
:jmdns_tutorials:compileTestJava NO-SOURCE
:jmdns_tutorials:processTestResources NO-SOURCE
:jmdns_tutorials:testClasses UP-TO-DATE
:jmdns_tutorials:test NO-SOURCE
:jmdns_tutorials:check UP-TO-DATE
:jmdns_tutorials:build

BUILD SUCCESSFUL

Total time: 2.368 secs
```

**Comment by ernestmc** [comment]
lgtm

**Pull request merged**
