### PR TITLE
Kinetic updates

### PR DESCRIPTION
**Pull request by adamantivm**

### CODE REVIEW

**Comment by stonier** [comment]
@adamantivm Went into the wrong branch - kinetic, not indigo.

**Comment by adamantivm** [comment]
reverted, sorry about that (again)

**Comment by stonier** [comment]
As an aside too...when you do a bump version commit, put the actual version number in the string message. Easy to inspect from the commit list then.

**Comment by adamantivm** [comment]
@stonier gotcha, thanks.

**Pull request merged**
