### PR TITLE
Kinetic updates

### PR DESCRIPTION
**Pull request by adamantivm**
Into kinetic branch instead now, @stonier want to double check?

### CODE REVIEW

**Comment by adamantivm** [comment]
I signed it!

**Comment by adamantivm** [comment]
I signed a corporate CLA under the corporation name Creativa 77 SRL. I am pretty sure this was already signed before, but I did it again just in case since the googlebot wasn't finding it.

**Comment by stonier** [comment]
Do you have an email registered for that Creativa 77 CLA and it is the same when set by `git config`?

**Comment by adamantivm** [comment]
Yes I do. I also signed a new CLA just in case. I'm going to now sign, in addition, an individual CLA to see if that helps make the googlebot happy for now.

**Pull request merged**
